---
title: "EU-EpiCap report"
output: html_document
---

```{r set-up, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, error=FALSE, echo=FALSE)
library(flexdashboard)
```

## EU-EpiCap Index and Dimensions
```{r overall-text}
restxt_overall_reactive()
```

<div class = "row">
<div class = "col-md-4">
</div>
<div class = "col-md-4">
```{r index-gauge}
g_index()
```
</div>
<div class = "col-md-4">
</div>
</div>

<div class = "row">
<div class = "col-md-4">
```{r dim1-gauge}
g_org()
```
</div>
<div class = "col-md-4">
```{r dim2-gauge}
g_ope()
```
</div>
<div class = "col-md-4">
```{r dim3-gauge}
g_imp()
```
</div>
</div>


## Targets
<div class = "row">
<div class = "col-md-6">
<center>
```{r target-lollipop, out.width="50%"}
lollipop<-print(lollipopreactive_tar())
lollipop
```
</center>
</div>

<div class = "col-md-6">
<center>
```{r target-radar, out.width="50%"}
r_all<-print(radreactive_all(),width=0.5)
r_all
```
</center>
</div>
</div>

## Dimension 1: Organization
<div class = "row">
<div class = "col-md-6">
<center>
```{r dim1-text}
```
</center>
</div>
<div class = "col-md-6">
<center>
```{r dim1-radar}
r1<-print(radreactive_1())
r1
```
</center>
</div>
</div>

## Dimension 2: Operations
<div class = "row">
<div class = "col-md-6">
<center>
```{r dim2-text}
```
</center>
</div>
<div class = "col-md-6">
<center>
```{r dim2-radar}
r2<-print(radreactive_2())
r2
```
</center>
</div>
</div>

## Dimension 3: Impact
<div class = "row">
<div class = "col-md-6">
<center>
```{r dim3-text}
```
</center>
</div>
<div class = "col-md-6">
<center>
```{r dim3-radar}
r3<-print(radreactive_3())
r3
```
</center>
</div>
</div>
